---
minio:
  address: 0.0.0.0
  port: 9000   
  accessKey: worldsbestaccesskey
  secretKey: worldsbestsecretkey
  ssl: false
  bucket: gleaner
gleaner:
  runid: runX # this will be the bucket the output is placed in...
  summon: true # do we want to visit the web sites and pull down the files
  mill: true
context:
  cache: true
contextmaps:
- prefix: "https://schema.org/"
  file: "./configs/schemaorg-current-https.jsonld"
- prefix: "http://schema.org/"
  file: "./configs/schemaorg-current-https.jsonld"
summoner:
  after: ""      # "21 May 20 10:00 UTC"   
  mode: full  # full || diff:  If diff compare what we have currently in gleaner to sitemap, get only new, delete missing
  threads: 5
  delay:  # milliseconds (1000 = 1 second) to delay between calls (will FORCE threads to 1) 
  headless: http://127.0.0.1:9222  # URL for headless see docs/headless
millers:
  graph: true
# will be built from sources.csv
#sitegraphs:
#- name: aquadocs
#  url: https://oih.aquadocs.org/aquadocs.json
#  headless: false
#  pid: http://hdl.handle.net/1834/41372
#  properName: AquaDocs
#  domain: https://aquadocs.org
#sitemaps:
#- name: samplesearth
#  url: https://samples.earth/sitemap.xml
#  headless: false
#  pid: https://www.re3data.org/repository/samplesearth
#  properName: Samples Earth (DEMO Site)
#  domain: https://samples.earth
