minio:
  accesskey: worldsbestaccesskey
  address: 0.0.0.0
  bucket: gleaner
  port: 9000
  secretkey: worldsbestsecretkey
  ssl: false
objects:
  bucket: gleaner
  domain: us-east-1
  # prefix will be built using the sources.csv, and additional values
  prefix:
  - orgs
  - summoned/obps
  - prov/obps
  - summoned/aquadocs
  - prov/aquadocs
  - milled/marinetraining
  - prov/marinetraining
  - milled/obis
  - prov/obis
  - milled/oceanexperts
  - prov/oceanexperts
sparql:
  endpoint: http://192.168.86.45:32775/blazegraph/namespace/lipd/sparql
txtaipkg:
  endpoint: http://0.0.0.0:8000
