version: '3'

  # This compose file needs variables set either in the shell 
  # or via a .env file.  See: https://docs.docker.com/compose/environment-variables/
  # for more details.
  #
  # ${MINIO_ACCESS_KEY}  
  # ${MINIO_SECRET_KEY}
  # ${GLEANER_OBJECTS}
  # ${GLEANER_GRAPH}

services:
  triplestore:
    image: nawer/blazegraph 
    environment:
      JAVA_XMS: 2g
      JAVA_XMX: 8g
      JAVA_OPTS: -Xmx6g -Xms2g --XX:+UseG1GC
    ports:
      - 9999:9999
    volumes:
      - ${GLEANER_GRAPH}:/var/lib/blazegraph
    networks:
      - traefik_default

  s3system:
    image: minio/minio:latest
    ports:
      - 54321:54321
      - 9000:9000
    volumes:
      - ${GLEANER_OBJECTS}:/data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
        - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    networks:
      - traefik_default
    command: ["server", "/data", "--console-address", ":54321"]

  headless:
    image: chromedp/headless-shell:latest
    labels:
      - "traefik.backend=headlesschrome"
      - "traefik.port=9222"
    ports:
      - 9222:9222
    environment:
     - SERVICE_PORTS=9222
    networks:
      - traefik_default    

networks:
  traefik_default:
