name: Release Gleaner Console binaries

on:
   release:
     types: [published]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux, windows, darwin]
        goarch: [amd64,arm64]
#        goos: [linux]
#        goarch: [amd64]
        exclude:
          - goarch: "386"
            goos: darwin
    steps:
      - uses: actions/checkout@v2
      - name: donwload schema
        run: curl -O https://schema.org/version/latest/schemaorg-current-https.jsonld
 #     - name: Run tests
  #      run: go test -v -p=1 -timeout=0 ./...
      - uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/glcon"
          binary_name: "glcon"
          ldflags: "-s -w"
          extra_files: README.md docs/ configs/ scripts/ schemaorg-current-https.jsonld
  #         extra_files: LICENSE README.md
